apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapplegacy-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - refactorizacion-app-gateway
  http:
  - match:
    - uri:
        prefix: "/webapplegacy-service"
    rewrite:
      uri: "/webapp/v2/webAppLegacy/producto"
    route:
    - destination:
        host: webapplegacy-service.web-app-space.svc.cluster.local
        port:
          number: 80