apiVersion: v1
kind: ConfigMap
metadata:
  name: webapplegacy-environment
  namespace: web-app-space
  annotations:
    strategy.spinnaker.io/versioned: "false"
  labels:
    app: webapplegacy-service
data:
  APP_HOST: "localhost" #localhost:8080 para que funcione el portforward
  APP_PORT: "8080"
  HOSTNAME_BASE: "webapp-pp.dominio.com"
  ENV: "production"
  URI_POD: "webapplegacy-service.web-app-space.svc.cluster.local:80"
  WSNAME: "prodWebservice"
  HTTP_CONSULTA_PRODUCTO: "https://producto-consulta-service.web-app-space.svc.cluster.local/product"
  HTTP_ALTA_PRODUCTO: "https://producto-alta-service.web-app-space.svc.cluster.local/product/create"
  HTTP_MODIFICATION_PRODUCTO: "https://producto-modificacion-service.web-app-space.svc.cluster.local/product/update"
  PWD_KEYSTORE: "password"
  BEGIN_CERTIFICATE: "-----BEGIN CERTIFICATE-----"
  END_CERTIFICATE: "-----END CERTIFICATE-----"
  BEGIN_RSA_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----"
  END_RSA_PRIVATE_KEY: "-----END RSA PRIVATE KEY-----"
  KEYBYTES: "1234556"
  IVBYTES: "1234556"
  CERTIFICATE_CRT: "1234556"
  CERTIFICATE_KEY: "1234556"
  CA_CRT: "1234556"
---
apiVersion: v1
kind: Service
metadata:
  name: webapplegacy-service
  namespace: web-app-space
spec:
  selector:
    app: webapplegacy-service
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplegacy-service-deployment
  namespace: web-app-space
  labels:
    app: webapplegacy-service
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: webapplegacy-service
  template:
    metadata:
      labels:
        app: webapplegacy-service
    spec:
      containers:
        - name: webapplegacy-service
          image: ggchavezhotmail/web-app-legacy:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"    
            limits:
              memory: "512Mi"
              cpu: "500m" 
          env:
            - name: TZ
              value: America/Santiago
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: APP_HOST
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: APP_PORT
            - name: HOSTNAME_BASE
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: HOSTNAME_BASE
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: ENV
            - name: URI_POD
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: URI_POD
            - name: WSNAME
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: WSNAME
            - name: HTTP_CONSULTA_PRODUCTO
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: HTTP_CONSULTA_PRODUCTO
            - name: HTTP_ALTA_PRODUCTO
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: HTTP_ALTA_PRODUCTO
            - name: HTTP_MODIFICATION_PRODUCTO
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: HTTP_MODIFICATION_PRODUCTO
            - name: KEYBYTES
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: KEYBYTES
            - name: IVBYTES
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: IVBYTES
            - name: CERTIFICATE_CRT
              valueFrom:            
                configMapKeyRef: 
                  name: webapplegacy-environment
                  key: CERTIFICATE_CRT
            - name: CERTIFICATE_KEY
              valueFrom:                
                configMapKeyRef:                  
                  name: webapplegacy-environment
                  key: CERTIFICATE_KEY
            - name: CA_CRT
              valueFrom:                
                configMapKeyRef:                  
                  name: webapplegacy-environment
                  key: CA_CRT
            - name: PWD_KEYSTORE
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: PWD_KEYSTORE  
            - name: BEGIN_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: BEGIN_CERTIFICATE  
            - name: END_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: END_CERTIFICATE  
            - name: BEGIN_RSA_PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: BEGIN_RSA_PRIVATE_KEY 
            - name: END_RSA_PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: webapplegacy-environment
                  key: END_RSA_PRIVATE_KEY
            - name: CATALINA_OPTS
              value: >-
                -Dcom.sun.management.jmxremote=true
                -Dcom.sun.management.jmxremote.port=9180
                -Dcom.sun.management.jmxremote.rmi.port=9180
                -Dcom.sun.management.jmxremote.ssl=false
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.jmxremote.host=0.0.0.0
                -Djava.rmi.server.hostname=127.0.0.1
                -Djava.net.preferIPv4Stack=true
          ports:
            - containerPort: 8080
            - containerPort: 9180
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /webapp/v2/webAppLegacy/producto
              port: 8080
              httpHeaders:
                - name: Accept
                  value: "*/*"
            initialDelaySeconds: 50
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 35
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /webapp/v2/webAppLegacy/producto
              port: 8080
              httpHeaders:
                - name: Accept
                  value: "*/*"
            initialDelaySeconds: 50
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 35
